@echo off
REM ==========================================================================
REM  ai-session-monitor -- portable machine setup. RUN AS ADMINISTRATOR
REM  (creating a logon Task Scheduler entry needs elevation on most machines).
REM
REM  New PC? 1) copy this whole folder  2) copy your config.local.json (secrets,
REM  never in git)  3) right-click this -> Run as administrator.
REM
REM  It (a) installs the Playwright Chromium browser, (b) generates the machine-
REM  local autostart launcher in %LOCALAPPDATA%, (c) registers a logon task that
REM  starts the monitor. Syncthing is included only if it's on PATH.
REM  Re-runnable; /F overwrites.
REM ==========================================================================
setlocal
set "DIR=%~dp0"
if "%DIR:~-1%"=="\" set "DIR=%DIR:~0,-1%"

REM --- locate pythonw (hidden) and syncthing (optional) ---
set "PYW="
for /f "delims=" %%i in ('where pythonw 2^>nul') do if not defined PYW set "PYW=%%i"
if not defined PYW (
  echo *** pythonw.exe not found on PATH. Install Python 3.10+ and retry. ***
  pause & exit /b 1
)
set "SYNC="
for /f "delims=" %%i in ('where syncthing 2^>nul') do if not defined SYNC set "SYNC=%%i"
echo Repo:      %DIR%
echo pythonw:   %PYW%
if defined SYNC echo syncthing: %SYNC%
echo.

echo [1/4] Installing Playwright Chromium...
"%PYW%" -m playwright install chromium
echo.

echo [2/4] Checking secrets file...
if exist "%DIR%\config.local.json" (echo   config.local.json found.) else (echo   *** WARNING: config.local.json MISSING -- copy from config.example.json and fill telegram_bot_token + telegram_chat_id ***)
echo.

echo [3/4] Writing autostart launcher...
set "APP=%LOCALAPPDATA%\ai-session-monitor"
if not exist "%APP%" mkdir "%APP%"
set "VBS=%APP%\autostart.vbs"
> "%VBS%" echo ' ai-session-monitor autostart (generated by install.bat; machine-local, not in git)
>> "%VBS%" echo Set sh = CreateObject("WScript.Shell")
>> "%VBS%" echo sh.Run "%PYW% ""%DIR%\monitor.py""", 0, False
if defined SYNC >> "%VBS%" echo sh.Run """%SYNC%"" serve --no-browser --no-restart", 0, False
echo   wrote %VBS%
echo.

echo [4/4] Registering logon task...
schtasks /Create /TN "ai-session-monitor" /SC ONLOGON /RL LIMITED /F /TR "wscript.exe \"%VBS%\""
if errorlevel 1 (
  echo   *** Task creation FAILED -- re-run this file AS ADMINISTRATOR. ***
) else (
  echo   Registered. Monitor starts hidden at next logon.
)
echo.
echo Done. Reminder: use autostart OR start-monitor.bat, not both (Telegram 409).
endlocal
pause
